return {
--     {
--     'rose-pine/neovim',
--     name = 'rose-pine',
--     lazy = false,
--     priority = 1000,
--     config = function()
--         require('rose-pine').setup {
--             variant = 'moon',
--             -- disable_background = true,
--             -- disable_float_background = false,
--             styles = {
--                 italic = false,
--                 transparency = true,
--             },
--             highlight_groups = {
--                 -- TreesitterContext = { bg = 'text' },
--                 -- TreesitterContextLineNumber = { bg = 'NONE' },
--                 --Dont use any theme for alacritty if you want this cursor
--                 --color to work.
--                 Cursor = { fg = "none", bg = "none" }, --cursor transparency
--                 Pmenu = {fg = "subtle", bg = "surface"},
--                 PmenuSel = {fg = "text", bg = "overlay"},
--                 -- Pmenu = {fg = "#908caa", bg = "#2a273f"},
--                 -- PmenuSel = {fg = "#e0def4", bg = "#393552"},
--                 StatusLine= { fg = "subtle", bg = "surface" }
--             },
--         }
--         vim.cmd.colorscheme 'rose-pine'
--     end,
-- },
-- {
--   "tjdevries/colorbuddy.nvim",
--     enabled = true,
--     priority = 1000,
--     config = function()
--       vim.cmd.colorscheme("colorbuddy")
--         end,
-- },
-- {
--     {
--     "sainnhe/gruvbox-material",
--     enabled = true,
--     priority = 1000,
--     config = function()
--       vim.g.gruvbox_material_transparent_background =0
--       vim.g.gruvbox_material_foreground = "mix"
--       vim.g.gruvbox_material_background = "hard"    -- soft, medium, hard
--       vim.g.gruvbox_material_ui_contrast = "low"   -- The contrast of line numbers, indent lines, etc.
--       vim.g.gruvbox_material_float_style = "bright" -- Background of floating windows
--       -- vim.g.gruvbox_material_statusline_style = "material"
--       vim.g.gruvbox_material_cursor = "auto"
--
--       -- vim.g.gruvbox_material_colors_override = { bg0 = '#000000' } -- #0e1010
--       -- vim.g.gruvbox_material_colors_override = { bg0 = "#121212" }
--       -- vim.g.gruvbox_material_better_performance = 1
--
--       vim.cmd.colorscheme("gruvbox-material")
--     end,
--   },
-- },

-- {
-- 	"rose-pine/neovim",
-- 	name = "rose-pine",
-- 	config = function()
-- 		require("rose-pine").setup({
-- 			disable_background = true,
-- 			styles = {
-- 				-- transparency = true,
-- 				italic = false,
-- 			},
--         highlight_groups = {
--             TreesitterContext = { bg = 'NONE' },
--             TreesitterContextLineNumber = { bg = 'NONE' },
--     }
-- 		})
-- 		vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "Float", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
-- 		vim.cmd("colorscheme rose-pine")
-- 	end,
-- },

--For tokyonight night
{
    "folke/tokyonight.nvim",
    config = function()
        require("tokyonight").setup({
            style = "night",
            styles = {
                functions = {}
            },
            lualine_bold = true,
        })
        vim.cmd("colorscheme tokyonight")
    end,
},
--
-- {
-- 	"folke/tokyonight.nvim",
-- 	config = function()
-- 		require("tokyonight").setup({
--             -- your configuration comes here
--             -- or leave it empty to use the default settings
--             style = "night", -- The theme comes in three styles, `storm`, `moon`, a darker variant `night` and `day`
--             -- transparent = false, -- Enable this to disable setting the background color
--             -- terminal_colors = true, -- Configure the colors used when opening a `:terminal` in Neovim
--             styles = {
--                 -- Style to be applied to different syntax groups
--                 -- Value is any valid attr-list value for `:help nvim_set_hl`
--                 comments = { italic = false },
--                 keywords = { italic = false },
--                 -- Background styles. Can be "dark", "transparent" or "normal"
--                 sidebars = "dark", -- style for sidebars, see below
--                 floats = "dark", -- style for floating windows
--             },
--             lualine_bold = true,
-- 		})
--         vim.cmd("colorscheme tokyonight")
--
--         -- vim.cmd("highlight Normal guibg=#1a1b26")
-- 	end,
-- },

-- {
--  	"folke/tokyonight.nvim",
--  	priority = 1000,
--  	config = function()
--
--  		require("tokyonight").setup({
--  			style = "night", -- The theme comes in three styles, `storm`, `moon`, a darker variant `night` and `day`
--  			light_style = "day", -- The theme is used when the background is set to light
--  			transparent = false, -- Enable this to disable setting the background color
--  			terminal_colors = true, -- Configure the colors used when opening a `:terminal` in [Neovim](https://github.com/neovim/neovim)
--  			styles = {
--  				comments = { italic = false },
--  				keywords = { italic = false },
--  				functions = {},
--  				variables = {},
--  				-- Background styles. Can be "dark", "transparent" or "normal"
--  				sidebars = "dark", -- style for sidebars, see below
--  				floats = "dark", -- style for floating windows
--  			},
--  		})
--  		-- vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
--  		vim.cmd("colorscheme tokyonight-night")
--  	end,
--  },

-- {
-- 	"ellisonleao/gruvbox.nvim",
-- 	priority = 1000,
-- 	config = function()
-- 		require("gruvbox").setup({
-- 			terminal_colors = true, -- add neovim terminal colors
-- 			undercurl = false,
-- 			underline = false,
-- 			bold = true,
-- 			italic = {
-- 				strings = false,
-- 				emphasis = false,
-- 				comments = false,
-- 				operators = false,
-- 				folds = false,
-- 			},
-- 			strikethrough = true,
-- 			invert_selection = false,
-- 			invert_signs = false,
-- 			invert_tabline = false,
-- 			invert_intend_guides = false,
-- 			inverse = true, -- invert background for search, diffs, statuslines and errors
-- 			contrast = "hard", -- can be "hard", "soft" or empty string
-- 			palette_overrides = {},
-- 			overrides = {
-- 				SignColumn = {},
-- 				-- ColorColumn = { bg = "#B7B644" },
-- 				-- LineNr = { fg = "#B7B644" },
-- 				-- statusline = { bg = "#302F2D" },
-- 			},
-- 			dim_inactive = false,
-- 			transparent_mode = false,
-- 		})
--
-- 		vim.o.background = "dark" -- or "light" for light mode
--
-- 		vim.cmd("colorscheme gruvbox")
-- 		vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
-- 	end,
-- },

-- return {
-- 	"folke/tokyonight.nvim",
-- 	priority = 1000,
-- 	config = function()
-- 		local transparent = true -- set to true if you would like to enable transparency
--
-- 		local bg = "#011628"
-- 		local bg_dark = "#011423"
-- 		local bg_highlight = "#143652"
-- 		local bg_search = "#0A64AC"
-- 		local bg_visual = "#275378"
-- 		local fg = "#CBE0F0"
-- 		local fg_dark = "#B4D0E9"
-- 		local fg_gutter = "#627E97"
-- 		local border = "#547998"
--
-- 		require("tokyonight").setup({
-- 			style = "night",
-- 			transparent = transparent,
-- 			styles = {
-- 				sidebars = transparent and "transparent" or "dark",
-- 				floats = transparent and "transparent" or "dark",
-- 			},
-- 			on_colors = function(colors)
-- 				colors.bg = bg
-- 				colors.bg_dark = transparent and colors.none or bg_dark
-- 				colors.bg_float = transparent and colors.none or bg_dark
-- 				colors.bg_highlight = bg_highlight
-- 				colors.bg_popup = bg_dark
-- 				colors.bg_search = bg_search
-- 				colors.bg_sidebar = transparent and colors.none or bg_dark
-- 				colors.bg_statusline = transparent and colors.none or bg_dark
-- 				colors.bg_visual = bg_visual
-- 				colors.border = border
-- 				colors.fg = fg
-- 				colors.fg_dark = fg_dark
-- 				colors.fg_float = fg
-- 				colors.fg_gutter = fg_gutter
-- 				colors.fg_sidebar = fg_dark
-- 			end,
-- 		})
--
-- 		vim.cmd("colorscheme tokyonight")
-- 	end,
-- }
-- {
-- 	"sainnhe/sonokai",
-- 	priority = 1000,
-- 	config = function()
-- 		vim.g.sonokai_transparent_background = "1"
-- 		vim.g.sonokai_enable_italic = "0"
-- 		vim.g.sonokai_style = "andromeda"
-- 		vim.cmd.colorscheme("sonokai")
--
-- 		vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 		vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
-- 	end,
-- },
--
-- {
-- 	"catppuccin/nvim",
-- 	name = "catppuccin",
-- 	priority = 1000,
-- 	lazy = false,
-- 	config = function()
-- 		local catppuccin = require("catppuccin")
-- 		local palettes = require("catppuccin.palettes")
-- 		local mocha = palettes.get_palette("mocha")
--
-- 		catppuccin.setup({
-- 			flavour = "mocha",
-- 			compile = { enabled = true, path = vim.fn.stdpath("cache") .. "/catppuccin" },
-- 			transparent_background = false,
-- 			term_colors = false,
-- 			integrations = {
-- 				aerial = false,
-- 				bufferline = true,
-- 				cmp = true,
-- 				dap = { enabled = true, enable_ui = true },
-- 				gitsigns = true,
-- 				lsp_trouble = true,
-- 				markdown = false,
-- 				mason = true,
-- 				mini = true,
-- 				native_lsp = { enabled = true },
-- 				notify = true,
-- 				rainbow_delimiters = true,
-- 				semantic_tokens = true,
-- 				telescope = true,
-- 				treesitter = true,
-- 				which_key = true,
-- 			},
-- 			highlight_overrides = {
-- 				mocha = {
-- 					DiagnosticVirtualTextError = { bg = mocha.base, style = {} },
-- 					DiagnosticVirtualTextWarn = { bg = mocha.base, style = {} },
-- 					DiagnosticVirtualTextInfo = { bg = mocha.base, style = {} },
-- 					DiagnosticVirtualTextHint = { bg = mocha.base, style = {} },
-- 					DiagnosticFloatingError = { bg = mocha.base, style = {} },
-- 					DiagnosticFloatingWarn = { bg = mocha.base, style = {} },
-- 					DiagnosticFloatingInfo = { bg = mocha.base, style = {} },
-- 					DiagnosticFloatingHint = { bg = mocha.base, style = {} },
-- 				},
-- 			},
-- 		})
--
-- 		-- vim.g.catppuccin_flavour = "macchiato"
-- 		vim.cmd([[colorscheme catppuccin]])
--
-- 		vim.api.nvim_set_hl(0, "LeapBackdrop", { link = "Comment" })
-- 		vim.api.nvim_set_hl(0, "LspInlayHint", { link = "Comment" })
-- 		-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 		-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- 	end,
-- },

-- function ColorMyPencils(color)
-- 	color = color or "rose-pine"
-- 	vim.cmd.colorscheme(color)
-- end
--
-- return {
-- 	"rose-pine/neovim",
-- 	name = "rose-pine",
-- 	config = function()
-- 		require("rose-pine").setup({
-- 			disable_background = true,
-- 			-- disable_float_background = true,
-- 			styles = {
-- 				italic = false,
-- 				transparency = false,
-- 			},
-- 			highlight_groups = {
-- 				Cursor = { fg = "black", bg = "#ffffff" }, -- Cursor color white
-- 			},
-- 		})
-- 		vim.cmd("colorscheme rose-pine")
-- 		ColorMyPencils()
-- 	end,
-- }
--
-- return {
--   "rebelot/kanagawa.nvim", -- Repositorio del colorscheme
--   lazy = false,
--   priority = 1000, -- Cargar este plugin antes que el resto
--   config = function()
--     require("kanagawa").setup({
--       compile = false, -- enable compiling the colorscheme
--       undercurl = true, -- enable undercurls
--       commentStyle = { italic = true },
--       functionStyle = {},
--       keywordStyle = { italic = true },
--       statementStyle = { bold = false },
--       typeStyle = {},
--       transparent = true, -- do not set background color
--       dimInactive = false, -- dim inactive window `:h hl-NormalNC`
--       terminalColors = true, -- define vim.g.terminal_color_{0,17}
--       colors = { -- add/modify theme and palette colors
--         palette = {},
--         theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
--       },
--       overrides = function(colors) -- add/modify highlights
--         return {}
--       end,
--       theme = "wave", -- Load "wave" theme when 'background' option is not set
--       background = { -- map the value of 'background' option to a theme
--         dark = "wave", -- try "dragon" !
--         light = "lotus",
--       },
--     }) -- Carga el colorscheme automáticamente
--
--         vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
--         vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
--     vim.cmd("colorscheme kanagawa-dragon") -- El colorscheme a utilizar
--   end,
-- }
-- return {
--   "notken12/base46-colors",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     -- Carga el colorscheme automáticamente
-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
--
--     vim.cmd("colorscheme ayu_dark") -- El colorscheme a utilizar
--   end,
-- }
}

